const VERSION='6.3.1';
const SHELL=`mythos-shell-${VERSION}`;
const RUNTIME=`mythos-runtime-${VERSION}`;
const SHELL_FILES=['./','./index.html','./manifest.webmanifest','./version.json','./icons/favicon.png','./icons/apple-touch-icon.png','./icons/icon-192.png','./icons/icon-512.png'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(SHELL).then(c=>c.addAll(SHELL_FILES)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>(k.startsWith('mythos-shell-')||k.startsWith('mythos-runtime-'))&&(k!==SHELL&&k!==RUNTIME)).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});return response}catch(e){return (await cache.match(request))||(await cache.match('./index.html'))}}
async function cacheFirst(request){const cache=await caches.open(RUNTIME);const hit=await cache.match(request);if(hit)return hit;const response=await fetch(request);if(response.ok)cache.put(request,response.clone());return response}
async function staleWhileRevalidate(request){const cache=await caches.open(RUNTIME);const hit=await cache.match(request);const network=fetch(request).then(response=>{if(response.ok)cache.put(request,response.clone());return response}).catch(()=>null);return hit||(await network)}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith('/version.json')){event.respondWith(fetch(event.request,{cache:'no-store'}));return}if(event.request.mode==='navigate'||url.pathname.endsWith('/index.html')){event.respondWith(networkFirst(event.request));return}if(event.request.destination==='image'||url.pathname.includes('/artworks/')){event.respondWith(staleWhileRevalidate(event.request));return}event.respondWith(staleWhileRevalidate(event.request))});
